CREATE TABLE COUNTRY(
cn_id INTEGER NOT NULL
        PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
cn_code CHAR(2),
cn_name VARCHAR(40)
);

CREATE TABLE AIRPORT (
ap_id INTEGER NOT NULL
        PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
ap_name VARCHAR(40),
cn_id INTEGER NOT NULL,
FOREIGN KEY(cn_id)
REFERENCES COUNTRY(cn_id)
);

CREATE TABLE EMPLOYEE (
emp_id INTEGER NOT NULL
        PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
emp_surname VARCHAR(40),
emp_firstname VARCHAR(40),
cn_id INTEGER NOT NULL,
FOREIGN KEY(cn_id)
REFERENCES COUNTRY(cn_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE SPOKEN_LANGUAGE (
lan_id INTEGER NOT NULL
        PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
lan_code CHAR(2),
lan_name VARCHAR(40)
);

CREATE TABLE EMPLOYEE_SPEAKS_LANGUAGE (
emp_id INTEGER NOT NULL,
lan_id INTEGER NOT NULL,
FOREIGN KEY(emp_id)
REFERENCES EMPLOYEE(emp_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
FOREIGN KEY(lan_id)
REFERENCES SPOKEN_LANGUAGE(lan_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);
